spring:
  profiles:
    active: dev
    include: private
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: simple

DEFAULT_SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket-name: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}

front-end:
  url: ${FRONTEND_URL}