INSERT INTO allergy (name, description) VALUES ('계란', '계란에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('우유', '우유 및 유제품에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('땅콩', '땅콩에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('대두', '대두(콩)에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('밀', '밀 및 밀가루에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('견과류', '견과류에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('갑각류', '새우, 게 등 갑각류에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('생선', '생선에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('조개류', '조개류에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('메밀', '메밀에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('참깨', '참깨 및 참기름에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('아황산염', '아황산염에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('복숭아', '복숭아에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('딸기', '딸기에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('포도', '포도에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('토마토', '토마토에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('키위', '키위에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('바나나', '바나나에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('사과', '사과에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('파인애플', '파인애플에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('호두', '호두에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('캐슈너트', '캐슈너트에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('피스타치오', '피스타치오에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('마카다미아', '마카다미아에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('헤이즐넛', '헤이즐넛에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('밤', '밤에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('코코넛', '코코넛에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('양고기', '양고기에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('돼지고기', '돼지고기에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('쇠고기', '쇠고기에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('닭고기', '닭고기에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('토끼고기', '토끼고기에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('참치', '참치에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('고등어', '고등어에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('연어', '연어에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('명태', '명태에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('청어', '청어에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('오징어', '오징어에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('문어', '문어에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('게', '게에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('새우', '새우에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('랍스터', '랍스터에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('홍합', '홍합에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('전복', '전복에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('굴', '굴에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('게맛살', '게맛살에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('치즈', '치즈에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('요거트', '요거트에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('버터', '버터에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('크림', '크림에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('꿀', '꿀에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('초콜릿', '초콜릿에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('커피', '커피에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('차', '차에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('소금', '소금에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('후추', '후추에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('고추', '고추에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('생강', '생강에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('마늘', '마늘에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('파', '파에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('양파', '양파에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('고수', '고수에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('로즈마리', '로즈마리에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('바질', '바질에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('파슬리', '파슬리에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('시금치', '시금치에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('당근', '당근에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('감자', '감자에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('고구마', '고구마에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('호박', '호박에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('양배추', '양배추에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('브로콜리', '브로콜리에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('피망', '피망에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('옥수수', '옥수수에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('가지', '가지에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('밀크초콜릿', '밀크 초콜릿에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('다크초콜릿', '다크 초콜릿에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('과일혼합물', '여러 과일의 혼합물에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('채소혼합물', '여러 채소의 혼합물에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('향신료', '다양한 향신료에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('식용유', '식용유에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('올리브유', '올리브유에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('포도씨유', '포도씨유에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('카놀라유', '카놀라유에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('해바라기씨유', '해바라기씨유에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('참기름', '참기름에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('버섯', '버섯에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('팥', '팥에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('녹두', '녹두에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('렌틸콩', '렌틸콩에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('완두콩', '완두콩에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('병아리콩', '병아리콩에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('구아검', '구아검에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('젤라틴', '젤라틴에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('카라기난', '카라기난에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('미역', '미역에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('김', '김에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('다시마', '다시마에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('차조기', '차조기에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('새싹채소', '새싹채소에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('시나몬', '시나몬에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('클로브', '클로브에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('육두구', '육두구에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('베이리프', '베이 리프에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('파프리카 가루', '파프리카 가루에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('카레 가루', '카레 가루에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('고춧가루', '고춧가루에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('계피', '계피에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('아니스', '아니스에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('허브', '허브에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('코코아', '코코아에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('아가베시럽', '아가베 시럽에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('메이플시럽', '메이플 시럽에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('감미료', '감미료에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('설탕', '설탕에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('인공 감미료', '인공 감미료에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('알코올', '알코올에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('맥주', '맥주에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('와인', '와인에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('사케', '사케에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('비타민C', '비타민 C에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('비타민D', '비타민 D에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('비타민B', '비타민 B군에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('프로폴리스', '프로폴리스에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('글루타민산', '글루타민산에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('MSG', 'MSG에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('베이킹파우더', '베이킹 파우더에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('베이킹소다', '베이킹 소다에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('효모', '효모에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('젖산', '젖산에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('유청', '유청에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('리보플라빈', '리보플라빈에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('카페인', '카페인에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('에너지 드링크', '에너지 음료에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('이온음료', '이온음료에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('소다', '소다 음료에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('탄산수', '탄산수에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('오렌지', '오렌지에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('레몬', '레몬에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('라임', '라임에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('그레이프프루트', '그레이프프루트에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('파파야', '파파야에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('망고', '망고에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('구아바', '구아바에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('코코넛 워터', '코코넛 워터에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('체리', '체리에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('블루베리', '블루베리에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('라즈베리', '라즈베리에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('블랙베리', '블랙베리에 대한 알레르기 반응');
INSERT INTO allergy (name, description) VALUES ('크랜베리', '크랜베리에 대한 알레르기 반응');